// Generated by CoffeeScript 1.7.1
(function() {
  var Fruit, db, models, mongodb,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mongodb = require('./index');

  Fruit = (function(_super) {
    __extends(Fruit, _super);

    function Fruit() {
      return Fruit.__super__.constructor.apply(this, arguments);
    }

    Fruit.prototype.model = 'Fruit';

    Fruit.defaults({
      handle: '',
      name: '',
      price: 0.00,
      description: '',
      images: []
    });

    return Fruit;

  })(mongodb.Model);

  models = {
    Fruit: Fruit
  };

  db = new mongodb.Database('testdata', models);

  db.setup(function() {
    return db.loadFiles('Fruit', {}, function(err, objs) {
      return console.log(err, objs);
    });
  });

}).call(this);
